---
version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - style
      - tests
      - memchecks:
          requires:
            - tests
jobs:
  lint:
    docker:
      - image: gcc:9
    parallelism: 1
    steps:
      - run: "apt-get update && apt-get install clang-tidy -y"
      - checkout
      - run: "[[ $(clang-tidy *.h *.c) ]] && exit 1"

  tests:
    docker:
      - image: gcc:9
    steps:
      - checkout
      - run: make tests
      - persist_to_workspace:
          root: bin
          paths:
            - "avocc_tests"

  memchecks:
    docker:
      - image: gcc:9
    steps:
      - attach_workspace:
          at: bin
      - run: "ls -la bin"
      - run: "apt-get update && apt-get install valgrind -y"
      - run: >
          G_DEBUG=gc-friendly valgrind -v \
            --tool=memcheck \
            --error-exitcode=1 \
            --leak-check=full \
            --num-callers=40 \
            bin/avocc_tests
